---
services:
  freqtrade-rsi:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-rsi
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8083:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_rsi.log
      --db-url sqlite:////freqtrade/user_data/tradesv3_rsi.sqlite
      --config /freqtrade/user_data/configs/config_rsi_bb.json
      --strategy RSIBBStrategy
